/**CONTROLADOR DE EL IFRAME DE LOS SEMAFOROS -> TRABAJOS:
 * 
 * - COMUNICARSE CON EL MODELO DE ALUMNOS PARA OBTENER LOS DATOS DE LOS SEMAFOROS DE LOS ALUMNOS
 * - CARGAR LOS SEMAFOROS Y LA INFORMACION DE CADA ALUMNOS POR MEDIO DE UN IFRAME
 * - ACTUALIZAR LOS SEMAFOROS EN TIEMPO REAL SI ES NECESARIO
 * - PODRIA DESARROLLARSE ALGUN CAMPO PARA FILTRAR LOS ALUMNOS POR NOMBRE, Y SITUACION DEL SEMAFORO
 * 
 * 
 */



